### PR TITLE
[WIP] Basic web app capability

### PR DESCRIPTION
**Pull request by JasperVanDenBosch**

### CODE REVIEW

**Comment by JasperVanDenBosch** [comment]
@mvdoc @dankessler Ok if we move the `tests` package to the root dir? In my experience this works better with CI

**Comment by mvdoc** [comment]
@ilogue yes sure

**Comment by JasperVanDenBosch** [comment]
I've added some things to a markdown readme for now, maybe someone can convert it to the .org (Emacs?)

**Comment by dankessler** [comment]
feel free to do the readme in markdown; I'm probably in the minority as a cranky emacs user

**Pull request merged**
